# *****************************************************************************
# CloudFlare DDNS Package
#
# Author: Steve Theisen (steve@tyzen9.com)
#         www.tyzen9.com - github.com/tyzen9
#
# Usage:
#   1. Place this package file in a config/packages folder
#   2. Add this to your configuration.yaml:
#      |homeassistant:
#      |  packages: !include_dir_named packages
#   3. Satisfy all dependant "external" entities (see note/examples below)
#   4. Restart Home Assistant
#   5. Drink a cold beverage
#
# Note: Packages require access to entities that are often configured outside
# of this file.  Manytimes, these are from common integrations such as ESPHome,
# Shelly, Zigbee, etc.  These dependant entities are called out in each package
# declaration below.
#
# Some Examples:
#   - ESPHome: https://www.home-assistant.io/integrations/esphome/
#
# *****************************************************************************

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# RESTful Sensors
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sensor:
  # ---------------------------------------------------------------------------
  # This rest call retrieves JSON associated to this container from socket-proxy 
  # and parses the desired json attributes.
  # Hint: post the url into a browser or postman to review the provided JSON
  #
  # Dependencies:
  #  - socket-proxy (see https://github.com/tyzen9/docker-insight)
  #  - secrets.yaml - used to store host names, etc.
  #  - secret_sensor_pkg.yaml - used to convert secret date to sensors 
  #       sensor.secret_host_1_socketproxy_url
  #
  # ---------------------------------------------------------------------------
  - platform: rest
    name: "Host 3 - CloudFlare DDNS - Current Digest"
    unique_id: "host_3_cloudflare_ddns_current_digest"
    resource_template: "http://niffler.lan:2375/images/{{ state_attr('sensor.host_3_cloudflare_ddns', 'image') }}/json"
    scan_interval: 7200
    value_template: "{{ value_json.RepoDigests[0].split('@')[1] }}"
    json_attributes_path: "$.Config.Labels"
    json_attributes:
      - org.opencontainers.image.version
    # Do not fire until the image name is evaluated (contains a '/' character)
    availability: >
      {{ state_attr('sensor.host_3_cloudflare_ddns', 'image') is string and '/' in state_attr('sensor.host_3_cloudflare_ddns', 'image') }}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Template Sensors
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
template:
  # ---------------------------------------------------------------------------
  # This sensor will update its state to the latest available repo digest ID
  # for this image when Diun sends an update FOR this image.
  #
  # ⚠️ This sensor will reset on restart (see the trigger sensor below)
  # ---------------------------------------------------------------------------
  - sensor:
    - name: "Host 3 - CloudFlare DDNS - Digest Update"
      unique_id: "host_3_cloudflare_ddns_digest_update"
      icon: mdi:barcode
      # If Diun pushes an update for THIS image, then store the new digest ID
      state: >
        {% from 'macros.jinja' import get_image_digest %}
        {{ get_image_digest('sensor.host_3_diun_update_handler', state_attr('sensor.host_3_cloudflare_ddns', 'image')) }}

  # ---------------------------------------------------------------------------  #
  # This TRIGGERED sensor watches for digest updates and stores the new digest ID
  # in a way that will survive home assistant restarts
  # ---------------------------------------------------------------------------  #
  - trigger:
      - trigger: state
        entity_id: sensor.host_3_cloudflare_ddns_digest_update
    sensor:
      - name: "Host 3 - CloudFlare DDNS - Latest Digest"
        unique_id: "host_3_cloudflare_ddns_latest_digest"
        state: "{{ states('sensor.host_3_cloudflare_ddns_digest_update') }}"

  # ---------------------------------------------------------------------------
  # This sensor determines the update status of this container/image and builds
  # a list of attributes useful for displaying on the dashboard
  # ---------------------------------------------------------------------------
  - sensor:
      - name: "Host 3 - CloudFlare DDNS - Update Summary"
        unique_id: "host_3_cloudflare_ddns_update_summary"
        state: >
          {% from 'macros.jinja' import is_update_available %}
          {{ is_update_available(states('sensor.host_3_cloudflare_ddns_current_digest'), states('sensor.host_3_cloudflare_ddns_latest_digest')) }}
        attributes:
          app_name: >
            {{ state_attr('sensor.host_3_cloudflare_ddns', 'friendly_name') }}
          version: >
            {% from 'macros.jinja' import get_container_version %}
            {{ get_container_version(
                'sensor.host_3_cloudflare_ddns_current_digest',
                'sensor.host_3_cloudflare_ddns'
              ) }}
          update_available: >
            {{ this.state }}
          container_state: >
            {{ states('sensor.host_3_cloudflare_ddns') or 'unknown'  }}
          status: >
            {{ state_attr('sensor.host_3_cloudflare_ddns', 'status') }}
          health: >
            {{ state_attr('sensor.host_3_cloudflare_ddns', 'health') }}
          memory: >
            {{ state_attr('sensor.host_3_cloudflare_ddns', 'memory') }}
          cpu: >
            {{ state_attr('sensor.host_3_cloudflare_ddns', '1cpu_percentage') }}
          current_digest: >
            {{ states('sensor.host_3_cloudflare_ddns_current_digest') or 'unknown'  }}
          latest_digest: >
            {{ states('sensor.host_3_cloudflare_ddns_latest_digest') or 'unknown'  }}
          release_notes: >
            {{ states('input_text.cloudflare_ddns_release_notes_url') or 'unknown'  }}
          host: > 
            {{ states('sensor.secret_host_3_hostname') or 'unknown'  }}
        icon: >
          {{ 'mdi:arrow-up-circle' if this.state == 'yes' else ('mdi:help-circle' if this.state == 'unknown' else 'mdi:check-circle') }}


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# AUTOMATIONS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
automation:
  # ---------------------------------------------------------------------------
  # Generate notification(s) when an update for this container is available
  # ---------------------------------------------------------------------------
  - alias: "Host 3 - CloudFlare DDNS - Update Notification"
    id: host_3_cloudflare_ddns_update_notification
    description: "Create a dashboard notifications when this container is ready for an update"
    mode: single
    trigger:
      platform: state
      entity_id: sensor.host_3_cloudflare_ddns_update_summary
      to: 'yes'
    action:
      # Create a dashboard notification
      - service: persistent_notification.create
        data:
          title: "CloudFlare DDNS Update Available"
          message: >
            A new version of CloudFlare DDNS is available (via Docker/Portainer)
          notification_id: host_3_cloudflare_ddns_update_persistant_notification

  # ---------------------------------------------------------------------------
  # Clear notification(s) when this container has been updated
  # ---------------------------------------------------------------------------
  - alias: "Host 3 - CloudFlare DDNS - Clear Update Notification"
    id: host_3_cloudflare_ddns_clear_update_notification
    description: "Clear the dashboard notification when this container is updated"
    mode: single
    trigger:
      platform: state
      entity_id: sensor.host_3_cloudflare_ddns_update_summary
      to: 'no'
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: host_3_cloudflare_ddns_update_persistant_notification
